spring:
  datasource:
    url: jdbc:h2:mem:cinemadb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

  mail:
    host: live.smtp.mailtrap.io
    port: 587
    username: smtp@mailtrap.io
    password: 121c34eee9bf232e5343f0883500bd21
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
